# Generated by Django 6.0.7 on 2026-07-25 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_animal_measure_feedtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='e.g. 25 for a 25kg bag, 50 for a 50kg bag', max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.feedtype')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.measure')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.store')),
            ],
            options={
                'unique_together': {('store', 'feed_type', 'amount', 'measure')},
            },
        ),
    ]
