# Generated by Django 6.0.7 on 2026-07-28 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='product.order'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('prepaid', 'Prepaid')], default='paid', max_length=10),
            preserve_default=False,
        ),
    ]
