# Generated by Django 6.0.7 on 2026-08-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='feed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='product.feedtype'),
        ),
    ]
