# Generated by Django 6.0.7 on 2026-08-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_review_feed_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_dashboard', 'Can view dashboard')]},
        ),
    ]
