# Generated by Django 6.0.7 on 2026-08-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_quantity_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_dashboard', 'Can view dashboard'), ('can_view_admin_panel', 'Can view admin panel link')]},
        ),
    ]
