# Generated by Django 6.0.7 on 2026-08-11 03:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Source Store Review'), ('SOURCE_APPROVED', 'Approved by Source Store Manager'), ('SOURCE_REJECTED', 'Rejected by Source Store Manager'), ('ADMIN_APPROVED', 'Approved by Admin (Completed)'), ('ADMIN_REJECTED', 'Rejected by Admin')], default='PENDING', max_length=20)),
                ('source_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_review_note', models.CharField(blank=True, max_length=255)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_admin_reviewed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_created', to=settings.AUTH_USER_MODEL)),
                ('requesting_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_made', to='product.store')),
                ('source_product', models.ForeignKey(help_text='The specific Product row (store + feed type + amount + measure) being requested from', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_received', to='product.product')),
                ('source_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_source_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
