# Generated by Django 6.0.7 on 2026-08-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_stocktransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_date',
            field=models.DateField(blank=True, help_text='Date the client wants this order ready/delivered. Leave blank for ASAP.', null=True),
        ),
    ]
