# Generated by Django 6.0.7 on 2026-08-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_order_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('now', 'Order Now'), ('book', 'Book Now')], default='now', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='village',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
