# Generated by Django 6.0.7 on 2026-08-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_add_village_and_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_booking_days', models.PositiveIntegerField(default=5, help_text='Minimum number of days from today a booking date must be.')),
                ('max_booking_days', models.PositiveIntegerField(default=21, help_text='Maximum number of days from today a booking date can be.')),
                ('payment_reminder_hours', models.PositiveIntegerField(default=24, help_text='Hours before the requested date to prompt the client for payment.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Settings',
                'verbose_name_plural': 'Booking Settings',
            },
        ),
    ]
