# Generated by Django 6.0.7 on 2026-08-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_add_bookingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='stock_after',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restock',
            name='stock_before',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
